// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210411133453_create_users")]
    partial class create_users
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37e4f662-1987-4b9d-b245-ad6014f3217a"),
                            CreatedAt = new DateTime(2021, 4, 11, 10, 34, 50, 795, DateTimeKind.Local).AddTicks(2481),
                            Email = "admin@admin.com",
                            Name = "Admin",
                            Password = "$2a$11$x/mNDOsFXIO5ow/0XGkQ8OaSmNtrqBvE/HSHW7KMYw/iai8qiTuda",
                            UpdatedAt = new DateTime(2021, 4, 11, 10, 34, 50, 797, DateTimeKind.Local).AddTicks(2146)
                        },
                        new
                        {
                            Id = new Guid("6823c5ae-ca43-4287-82e1-10d5fca46a2e"),
                            CreatedAt = new DateTime(2021, 4, 11, 10, 34, 51, 88, DateTimeKind.Local).AddTicks(3142),
                            Email = "testUser01@email.com",
                            Name = "Test-User-01",
                            Password = "$2a$11$wAphH2ntzKu2SYorng/RPOeFkwWzfyYNpBIX.iOOMHX6E19NNuGom",
                            UpdatedAt = new DateTime(2021, 4, 11, 10, 34, 51, 88, DateTimeKind.Local).AddTicks(3182)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
