name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build ./base-api-netcore-ddd.sln --configuration Release

    - name: Test with dotnet
      run: dotnet test --filter AutoMapper ./base-api-netcore-ddd.sln --configuration Release &&
           dotnet test --filter Controller ./base-api-netcore-ddd.sln --configuration Release &&
           dotnet test --filter Service ./base-api-netcore-ddd.sln --configuration Release
           
    - name: Run Parasoft dotTEST
      uses: parasoft/run-dottest-action@1.1.0
      
